// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4y_76rghZHWWmTch6UT30dZdjf5PYA6g',
    appId: '1:505201455892:web:ce8317d62992e0f36f8801',
    messagingSenderId: '505201455892',
    projectId: 'twitmania-c101b',
    authDomain: 'twitmania-c101b.firebaseapp.com',
    storageBucket: 'twitmania-c101b.appspot.com',
    measurementId: 'G-GE6674G6CF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWQN0G4zp7HN_DUETmwHg9SCKMder8Ue8',
    appId: '1:505201455892:android:614286fe238cf56c6f8801',
    messagingSenderId: '505201455892',
    projectId: 'twitmania-c101b',
    storageBucket: 'twitmania-c101b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUWrt8nXfWfWux4i3mS7fDaPcDhl50jjI',
    appId: '1:505201455892:ios:a11725d43cdf10c46f8801',
    messagingSenderId: '505201455892',
    projectId: 'twitmania-c101b',
    storageBucket: 'twitmania-c101b.appspot.com',
    iosBundleId: 'com.example.twitmania',
  );
}
